In [1]:
import numpy as np

In [2]:
file_url='https://raw.githubusercontent.com/svkarthik86/Advanced-python/main/climate.txt'

In [23]:
climate=np.genfromtxt(file_url,delimiter=",",skip_header=1,dtype=int)

In [24]:
data=np.split(climate,10)

In [25]:
data

[array([[ 25,  76,  99],
        [ 39,  65,  70],
        [ 59,  45,  77],
        ...,
        [ 95, 100,  66],
        [ 75,  97,  24],
        [ 87,  59,  81]]),
 array([[ 93,  41,  94],
        [ 81,  47,  98],
        [ 65,  71,  91],
        ...,
        [ 57,  91,  27],
        [ 51,  92,  64],
        [100,  32,  82]]),
 array([[82, 21, 40],
        [76, 76, 93],
        [47, 24, 81],
        ...,
        [68, 59, 74],
        [49, 81, 28],
        [44, 27, 27]]),
 array([[38, 46, 21],
        [68, 75, 33],
        [29, 91, 68],
        ...,
        [97, 43, 47],
        [94, 90, 96],
        [74, 66, 87]]),
 array([[57, 98, 28],
        [51, 51, 22],
        [50, 79, 20],
        ...,
        [62, 34, 83],
        [98, 72, 23],
        [79, 47, 46]]),
 array([[ 27,  49,  71],
        [ 50,  77,  22],
        [ 91,  30,  87],
        ...,
        [ 53,  67,  60],
        [ 34,  33,  71],
        [100,  26,  77]]),
 array([[45, 75, 73],
        [45, 61, 73],
        [33, 98, 53]

In [ ]:
yield_crop=[]


In [7]:
header=np.genfromtxt(file_url,delimiter=",",skip_header=0,dtype="U")

In [8]:
header=",".join(header[0])

In [9]:
header

'temperature,rainfall,humidity'

In [10]:
count=1
for i in data:
    np.savetxt(f"Assignment/climate_project/climate_data_team{count}",i,delimiter=",",header=header)
    count+=1
    